### ISSUE TITLE
Question - support for forms based authentication and dismissing cookie banner?

### ISSUE THREAD

**Issue by meirion** [rytsikau/ee.Screen#3]
I need to take batch screenshots of a private portal - which requires a login, and also requires a cookie message to be dismissed. 

Can your script handle this or is there a way to support such a site? 

Thanks

**Comment by rytsikau** [comment]
You can try to create cookie file using browser, and then specify its location for the Puppeteer.
In Chrome, there is a useful add-on to do this, it can be found by keywords json+puppeteer
